KajBomoPaDnsJel/Models/Meni.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace KajBomoPaDnsJel.Models
{
    public class Meni
    {
        public Meni(string ImeMenija)
        {
            this.Ime = ImeMenija;
            this.IsFacebookPost = false;
            this.FacebookPostUrl = "";
        }
        public Meni(bool FacebookPost, string FacebookPostUrl)
        {
            this.Ime = "";
            this.IsFacebookPost = FacebookPost;
            this.FacebookPostUrl = FacebookPostUrl;
        }

        public string Ime { get; set; }
        public bool IsFacebookPost { get; set; }
        public string FacebookPostUrl { get; set; }
    }
}

KajBomoPaDnsJel/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace KajBomoPaDnsJel.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

KajBomoPaDnsJel/Controllers/MeniController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Web;
using System.Web.Mvc;
using KajBomoPaDnsJel.Models;
using static KajBomoPaDnsJel.BusinessLogic.MeniWebPageParser;

namespace KajBomoPaDnsJel.Controllers
{
    public class MeniController : Controller
    {
        // GET: Meni
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult Restavracija(int id)
        {
            WebPagesEnum restavracija;
            List<Meni> meniji = new List<Meni>();
            if (Enum.TryParse(id.ToString(), out restavracija))
            {
                ViewBag.restavracija = urlsWebPagesEnum[restavracija].FullName;
                meniji = GetMenuFromWebPage(restavracija);
            }
            else
            {
                // ni pravi Id restavracije
            }

            //meniji.Add(new Meni("tola jed"));

            return View(meniji);
        }

        public ActionResult SendMenus(string key_mails)
        {
            bool mailsSend = false;

            string[] key_mails_splitted = key_mails.Split(';');
            if (key_mails_splitted.Length == 2)
            {
                string key = key_mails_splitted[0];
                if (key != "5a0600ee-3a99-4d36-af1e-426f1d196d80")  // "5985cd81-d6c9-4fec-949b-602bfd12fe12"
                {
                    //return HttpNotFound("Failed call.");
                    ViewBag.notification = "Unvalid call!";
                    return View();
                }

                List<string> toMails = new List<string>();
                //toMails.Add("ales.koncilja@gmail.com");
                toMails.AddRange(key_mails_splitted[1].Split(',').ToList());

                StringBuilder sb_menu = new StringBuilder();
                List<Meni> meniji = new List<Meni>();
                bool obstajaVsajEnMeni = false;
                foreach (WebPagesEnum restavracija in urlsWebPagesEnum.Keys)
                {
                    //if (restavracija != WebPagesEnum.FlorjanckovHram)
                    //    continue;

                    meniji = GetMenuFromWebPage(restavracija);

                    // Element, Farao, Rogovilc, FlorjanckovHram
                    if (meniji.Count > 0)
                    {
                        obstajaVsajEnMeni = true;

                        sb_menu.AppendFormat("<h1>{0}:</h1>", urlsWebPagesEnum[restavracija].FullName);

                        sb_menu.Append("<ul>");
                        foreach (Meni m in meniji)
                        {
                            if (m.IsFacebookPost)
                            {
                                sb_menu.AppendFormat("<li><a href=\"{0}\">{1} menu</a></li>", m.FacebookPostUrl, urlsWebPagesEnum[restavracija].FullName);
                            }
                            else
                            {
                                sb_menu.AppendFormat("<li>{0}</li>", m.Ime);
                            }
                        }
                        sb_menu.Append("</ul>");
                        sb_menu.Append("<br /><br />");
                    }
                }

                if (!obstajaVsajEnMeni)
                {
                    sb_menu.AppendLine("Trenutno ni menijev!");
                }
                else
                {
                    sb_menu.AppendLine("Dober tek!");
                }


                sb_menu.Append("<br /><br /><br />");
                sb_menu.AppendLine(string.Format("Prenesi mobilno aplikacijo <a target=\"_blank\" title=\"Prenesi mobilno aplikacijo\" " +
                    "href=\"https://gonative.io/share/qoaped\"><i>Kaj bomo pa dns jel</i></a>."));

                sb_menu.Append("<br /><br />");
                sb_menu.AppendLine(string.Format("Obišči spletno stran <a href=\"https://kajbomopadnsjel.azurewebsites.net\">kajbomopadnsjel</a>."));
                sb_menu.Append("<br /><br />");

                sb_menu.Append("<img src=\"https://kajbomopadnsjel.azurewebsites.net/Images/dober-tek.jpg\" alt=\"Dober tek\">");
                try
                {
                    mailsSend = SendEmail(toMails, string.Format("Kaj bomo pa dns jel: {0}", DateTime.Now.ToString("dd.MM.yyyy")), sb_menu.ToString());
                    ViewBag.notification = mailsSend ? "Menuji poslani!" : "Pošiljanje mailov ni uspelo!";
                }
                catch (Exception e)
                {
                    ViewBag.notification += e.Message + "  " + e.ToString();
                }
            }
            else
            {
                return HttpNotFound("Failed call.");
            }
            return View();
        }

        // GET: Meni/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        // GET: Meni/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Meni/Create
        [HttpPost]
        public ActionResult Create(FormCollection collection)
        {
            try
            {
                // TODO: Add insert logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: Meni/Edit/5
        public ActionResult Edit(int id)
        {
            return View();
        }

        // POST: Meni/Edit/5
        [HttpPost]
        public ActionResult Edit(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add update logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: Meni/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: Meni/Delete/5
        [HttpPost]
        public ActionResult Delete(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add delete logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }
    }
}

KajBomoPaDnsJel/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}

<script type="text/javascript" src="https://platform.linkedin.com/badges/js/profile.js" async defer></script>

@*<h2>@ViewBag.Title.</h2>*@
@*<h3>@ViewBag.Message</h3>*@
<h2>About me</h2>

@*<p>Use this area to provide additional information.</p>*@
@*<p>Zaenkrat nič posebnega.</p>*@
<div class="LI-profile-badge" data-version="v1" data-size="medium" data-locale="en_US" data-type="vertical" data-theme="light" data-vanity="aleskoncilja"><a class="LI-simple-link" href='https://si.linkedin.com/in/aleskoncilja?trk=profile-badge'>Aleš Koncilja</a></div>    @*data-theme="dark"*@

KajBomoPaDnsJel/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
@*<h3>@ViewBag.Message</h3>*@

@*<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>*@

@*<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>*@
<address>
    <strong>Osebno:</strong>    <a href="mailto:ales.koncilja@gmail.com">Aleš - privatno</a><br />
    <strong>Službeno:</strong>  <a href="mailto:ales.koncilja@cgs-labs.com">Aleš - službeno</a>
</address>

KajBomoPaDnsJel/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}
@using KajBomoPaDnsJel.BusinessLogic;

<div class="jumbotron">
    <h1>Kaj bomo pa dns jel</h1>
    <p class="lead">Vsi meniji na enem kupu :)</p>
    @*<p><a href="https://asp.net" class="btn btn-primary btn-lg">Learn more &raquo;</a></p>*@
</div>

<div class="row">
    <div class="col-md-4">
        <h2>@Html.ActionLink("Element", "Restavracija", "Meni", new { id = (int)MeniWebPageParser.WebPagesEnum.Element }, null)</h2>
        <h2>@Html.ActionLink("Rogovilc", "Restavracija", "Meni", new { id = (int)MeniWebPageParser.WebPagesEnum.Rogovilc }, null)</h2>
        <h2>@Html.ActionLink("Farao", "Restavracija", "Meni", new { id = (int)MeniWebPageParser.WebPagesEnum.Farao }, null)</h2>
        <h2>@Html.ActionLink("Florjančkov Hram", "Restavracija", "Meni", new { id = (int)MeniWebPageParser.WebPagesEnum.FlorjanckovHram }, null)</h2>
        <p>@*<a class="btn btn-default" href="@Html.ActionLink("Home", "Index", "Home")">Element</a>*@</p>


    </div>

    <div class="col-md-4">
        <h2>Mobilna aplikacija</h2>
        <p>
            Sedaj je na voljo tudi mobilna aplikacija.
        </p>
        <p><a class="btn btn-default" title="Prenesi mobilno aplikacijo" target="_blank" href="https://gonative.io/share/qoaped">Prenesi mobilno aplikacijo</a></p>
    </div>

    @*<div class="col-md-4">
            <h2>Getting started</h2>
            <p>
                ASP.NET MVC gives you a powerful, patterns-based way to build dynamic websites that
                enables a clean separation of concerns and gives you full control over markup
                for enjoyable, agile development.
            </p>
            <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301865">Learn more &raquo;</a></p>
        </div>
        <div class="col-md-4">
            <h2>Get more libraries</h2>
            <p>NuGet is a free Visual Studio extension that makes it easy to add, remove, and update libraries and tools in Visual Studio projects.</p>
            <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301866">Learn more &raquo;</a></p>
        </div>
        <div class="col-md-4">
            <h2>Web Hosting</h2>
            <p>You can easily find a web hosting company that offers the right mix of features and price for your applications.</p>
            <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301867">Learn more &raquo;</a></p>
        </div>*@
</div>

KajBomoPaDnsJel/Views/Meni/Restavracija.cshtml
@model IEnumerable<KajBomoPaDnsJel.Models.Meni>

@*<p>
        @Html.ActionLink("Create New", "Create")
    </p>*@

@{
    ViewBag.Title = string.IsNullOrEmpty(ViewBag.restavracija) ? "Restavracija" : ViewBag.restavracija;
}
@{
    string naslov = "Meni";
    if (string.IsNullOrEmpty(ViewBag.restavracija))
    {
        naslov += "";
    }
    else
    {
        naslov += " " + ViewBag.restavracija;
    }
}

@*https://www.w3schools.com/bootstrap/bootstrap_carousel.asp*@
@*https://www.w3schools.com/w3css/w3css_slideshow.asp*@
@*https://css-tricks.com/snippets/jquery/simple-auto-playing-slideshow/*@

<script src="https://connect.facebook.net/en_US/sdk.js#xfbml=1&amp;version=v2.5" async></script>

<table class="table">
    <tr>
        <th>
            @*@Html.DisplayNameFor(model => model.Ime)*@
            @*@Html.DisplayName("Meni " + "ViewBag.restavracija"+":")*@
            @Html.DisplayName(naslov + ":")
        </th>
        <th></th>
    </tr>

    @if (Model.Count() == 0)
    {
        <tr>
            <td>
                <i>Za današnji dan ni objavljenega menija.</i>
            </td>
        </tr>
    }
    else
    {
        foreach (var item in Model)
        {
            <tr>
                <td>
                    @*@if (item.Ime.StartsWith("("))
                        {
                            <text>       </text>
                        }*@
                    @if (item.IsFacebookPost)
                    {
                        @*<text>1 @item.FacebookPostUrl</text>*@
                        <div class="fb-post" data-href="@item.FacebookPostUrl" data-width="500"></div>
                    }
                    @*else if (item.Ime.Contains("http"))
                        {
                            <text>2 @item.Ime</text>
                            <img src="@item.Ime" />
                            <div class="fb-post" data-href="@item.Ime" data-width="500"></div>
                        }*@
                    else
                    {
                        @*<text>3 @item.Ime</text>*@
                        @Html.DisplayFor(modelItem => item.Ime)
                    }
                </td>
                @*<td>
                        @Html.ActionLink("Edit", "Edit", new { /* id=item.PrimaryKey */ }) |
                        @Html.ActionLink("Details", "Details", new { /* id=item.PrimaryKey */ }) |
                        @Html.ActionLink("Delete", "Delete", new { /* id=item.PrimaryKey */ })
                    </td>*@
            </tr>
        }
    }

</table>

KajBomoPaDnsJel/Views/Meni/SendMenus.cshtml
@{
    ViewBag.Title = "Pošiljanje menujev";
}

<h3>@ViewBag.notification</h3>
<br />
<img src="~/Images/dober-tek.jpg" alt="Dober tek" />

KajBomoPaDnsJel/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Kaj bomo pa dns jel</title>

    <link rel="alternate" hreflang="si" href="https://dis-labs.com" />

    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Kaj bomo pa dns jel", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                    <li>@Html.ActionLink("About", "About", "Home")</li>
                    <li>@Html.ActionLink("Contact", "Contact", "Home")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - Kaj bomo pa dns jel</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>